spring.application.name=samabank-customer-service
server.port=8082

# Database
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/samabank
spring.datasource.username=${DB_USER:samabank}
spring.datasource.password=${DB_PASSWORD:samabank2025}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# JWT
samabank.jwt.secret=3JQfWwo6ng0zWr569ej3lexrVxZT4a+xBdvnfCgtU+/eKudJx7dREo8AZKgFXITAa9I1ARmdI9nhGuK61VifMw==
samabank.jwt.access-token-ttl=900
samabank.jwt.refresh-token-ttl=604800

# CORS
samabank.cors.allowed-origins=http://localhost:4200

# Actuator
management.endpoints.web.exposure.include=health,info

# Logging
logging.level.sn.samabank=DEBUG
