package sn.samabank.notification.entity;

public enum NotificationType {
    WELCOME, DEPOSIT_CONFIRMATION, WITHDRAWAL_CONFIRMATION, TRANSFER_CONFIRMATION,
    ACCOUNT_OPENED, ACCOUNT_SUSPENDED, LOGIN_ALERT, ACCOUNT_LOCKED, PASSWORD_RESET
}
